rlgame: *.cpp *.hpp
	g++ *.cpp *.hpp \
	-l sfml-graphics -l sfml-system -l sfml-window \
	-std=c++14 \
	-I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m \
	-I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m \
	-I./tiny-dnn \
	-L/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin \
	-lpython3.6m -ldl \
	-framework CoreFoundation